import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

const CoolBeans = dynamic(() => import("../components/CoolBeans"), {
  suspense: true,
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Suspense fallback={"loading…"}>
          <CoolBeans />
        </Suspense>
      </Head>
    </div>
  );
};

export default Home;
